[package]
name = "voice-hub-desktop"
version = "1.7.0"
description = "Voice Hub desktop shell"
authors = ["RainyHorizon"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
