export type Voice = {
  id: string;
  provider: string;
  model_id: string;
  display_name: string;
  public_name: string;
  voice_type: string;
  status: string;
  languages: string[];
  preview_url?: string | null;
  design_prompt?: string;
  provider_account_id?: string | null;
  provider_project_name?: string | null;
  provider_voice_id?: string | null;
};
export type Model = {
  provider: string;
  model_id: string;
  gateway_id: string;
  display_name: string;
  quality: string;
  latency: string;
  supports_clone: boolean;
  mode: "demo" | "provider";
  operations: string[];
  design_prompt_max?: number | null;
  design_preview_min?: number | null;
  design_preview_max?: number | null;
};
export type CloneConfig = {
  provider: string;
  model_id: string;
  display_name: string;
  public_name: string;
  speaker_id?: string;
  provider_account_id?: string;
  provider_project_name?: string;
  clone_language?: number;
};
export type DesignConfig = {
  provider: string;
  model_id: string;
  prompt: string;
  preview_text: string;
  display_name: string;
  public_name: string;
};
export type ImportVoiceConfig = CloneConfig & {
  provider_voice_id: string;
  languages: string[];
};
export type CloudVoice = {
  provider?: string;
  provider_voice_id: string;
  model_id: string;
  display_name: string;
  language: string;
  created_at: string;
  compatible: boolean;
  compatibility_message: string;
  imported: boolean;
  provider_account_id?: string;
  provider_project_name?: string;
};
export type VolcengineSlot = {
  speaker_id: string;
  state: string;
  alias: string;
  available_training_times: number | null;
  expire_time?: string | number;
  is_activatable?: boolean | null;
  instance_no?: string;
  version?: string;
};
export type Job = {
  id: string;
  model: string;
  voice: string;
  input_chars: number;
  status: string;
  duration_ms: number;
  created_at: string;
  source: string;
  input_text?: string;
  created_date?: string;
  audio_available?: boolean;
  audio_url?: string | null;
  text_url?: string | null;
  audio_cleaned_at?: string | null;
  audio_cleanup_reason?: string | null;
};
export type StoragePolicy = {
  automatic_enabled: boolean;
  retention_days: number;
  capacity_limit_bytes: number;
  interval: "daily" | "weekly";
  cleanup_scope: "audio_only" | "jobs";
  updated_at: string;
};
export type StorageUsage = {
  job_count: number;
  audio_count: number;
  audio_bytes: number;
  directory_file_count: number;
  directory_bytes: number;
  unmanaged_bytes: number;
  missing_audio_count: number;
  oldest_audio_at?: string | null;
  capacity_ratio: number;
};
export type CleanupRun = {
  id: string;
  trigger: "manual" | "automatic";
  status: string;
  files_removed: number;
  jobs_removed: number;
  jobs_preserved: number;
  bytes_freed: number;
  completed_at: string;
  message: string;
};
export type StorageStatus = {
  policy: StoragePolicy;
  usage: StorageUsage;
  next_cleanup_at?: string | null;
  cleanup_history: CleanupRun[];
  storage_path: string;
};
export type CleanupPreview = {
  file_count: number;
  job_count: number;
  jobs_preserved: number;
  bytes_before: number;
  bytes_to_free: number;
  bytes_after: number;
  retention_cutoff: string;
  cleanup_scope: "audio_only" | "jobs";
};
export type Gateway = {
  enabled: boolean;
  base_url: string;
  key: string;
  mode: string;
  note: string;
  key_hint?: string;
  key_source?: string;
  managed?: boolean;
};
export type LatencyStats = { p50: number | null; p95: number | null; samples: number };
export type GatewayStatsBucket = {
  name: string;
  requests: number;
  completed: number;
  failed: number;
  cancelled: number;
  success_rate: number;
  first_chunk_latency: LatencyStats;
  total_latency: LatencyStats;
};
export type GatewayStats = {
  window: string;
  provider: string | null;
  sample_count: number;
  total_requests: number;
  completed_requests: number;
  failed_requests: number;
  cancelled_requests: number;
  success_rate: number;
  first_chunk_latency: LatencyStats;
  total_latency: LatencyStats;
  by_provider: GatewayStatsBucket[];
  by_model: GatewayStatsBucket[];
  errors: Array<{ code: string; count: number; last_seen_at: string }>;
};
export type ProviderAccount = {
  id: string;
  provider: string;
  display_name: string;
  account_ref?: string;
  region?: string;
  endpoint?: string;
  status: string;
  secret_hint: string;
  verification_scope: string;
  verification_message?: string;
  last_verified_at?: string;
  project_name?: string;
  openapi_access_key_hint?: string;
  has_openapi_secret?: boolean;
  project_count?: number;
};
export type ProviderProject = {
  id: string;
  provider_account_id: string;
  project_name: string;
  display_name: string;
  status: string;
  has_permission?: boolean | null;
  source: string;
  last_synced_at?: string | null;
  has_api_key?: boolean | null;
  api_key_status?: "available" | "missing" | "unknown" | "error";
  api_key_name?: string | null;
  api_key_hint?: string | null;
  api_key_count?: number;
  api_key_last_synced_at?: string | null;
  api_key_sync_error?: string | null;
};
export type ProviderSpec = {
  display_name: string;
  secret_label: string;
  default_endpoint: string;
  endpoint_note: string;
  verification: string;
};
export type DiagnosticCheck = {
  id: string;
  label: string;
  status: "ok" | "warning" | "error";
  version: string;
  detail: string;
};
export type SystemDiagnostics = {
  status: "ok" | "warning" | "error";
  platform: string;
  base_url: string;
  port: number;
  checks: DiagnosticCheck[];
  required_failures: number;
  demo: { model: string; voice: string; available: boolean };
};
